# Generated by Django 5.0 on 2023-12-11 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='website',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
