# Generated by Django 5.0 on 2023-12-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_created_at_article_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_last_run',
            field=models.BooleanField(default=False),
        ),
    ]
