# Generated by Django 5.0 on 2023-12-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_is_last_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='partial_ratio',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='ratio',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='token_set_ratio',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='token_sort_ratio',
            field=models.FloatField(default=0),
        ),
    ]
